### ISSUE TITLE
About the performance of SimCLR

### ISSUE THREAD

**Issue by scnuhealthy** [open-mmlab/mmselfsup#17]
This is a wonderful project!
I found a bug in the code. The word 'CosineAnealing' in the config file 'configs/selfup/moco/r50_v2.py' should be 'CosineAnnealing', and I think this bug results from the spelling error fixed in mmvc.
And here I am confused about the performance of SimClR, which is much lower than that printed in the paper (e.g. 64.5% vs 75.5, the Top-5 accuracy on semi-supervised learning on ImageNet 1%). Is it mainly because of the batch size (the batch size of your reproduction is only 256)?
Looking forward to your reply!

**Comment by XiaohangZhan** [comment]
Thank you for your remind. I fixed it just now.
Because in our implementation, the batch size is 256, the total epoch is 200, while in SimCLR full setting, the batch size is 4096, the epoch is 1000. In our setting, the result of linear classification in ImageNet is consistent with that officially reported by SimCLR. We are not able to run the full setting for now. Besides, the evaluation setting is also different from that of SimCLR which also requires a large number of computation resources. We set up a new evaluation protocol applicable to all methods for fair comparison.

**Comment by scnuhealthy** [comment]
Thanks for your reply.
And I am also curious about why the learning rate is 30.0 in the config file /benchmarks/linear_classification/imagenet/r50_moco.py on the ImageNet linear classification task (for evaluation of the representation learning). The learning rate is too high while that of SimCLR is only 0.1 × batchsize/256. So if my batchsize is also set as 256, is 30.0 a appropriate figure?

**Comment by scnuhealthy** [comment]
Thanks for your answers.
