### ISSUE TITLE
Any Plans about AMP support?

### ISSUE THREAD

**Issue by cxxgtxy** [open-mmlab/mmselfsup#30]
Many projects of MMLAB use nvidia apex to support AMP. 
I wonder whether there is a plan about supporting it in this project.
Thanks!

**Comment by XiaohangZhan** [comment]
Indeed it is really desirable to support apex. However, since I've graduated and engaged in my work already, I'm afraid I'm not able to spend a lot of time on it. You are welcome to contribute to this repo, e.g., integrating apex into it. Your contribution will be recorded and recognized. I will be really grateful if others outside the MMLAB can contribute to making this repo better. After all, self-supervised learning is an important and interesting topic.

**Comment by XiaohangZhan** [comment]
AMP supported now.
