### ISSUE TITLE
Semi supervised segmentation

### ISSUE THREAD

**Issue by shengyi4** [open-mmlab/mmselfsup#300]
Can this approach be used in semi-supervised image segmentation, such as deeplabv3, segformer, and so on?
Thanks!

**Comment by MengzhangLI** [comment]
I think it can't support because MMSelfSup is designed for upstream self-supervised learning and semi-supervised semantic segmentation usually focuses on partial images with labels and the other without labels, where most algorithms are proposed on relation between fully supervised part and self supervised part.
